/*
 * Audit Service
 * Сервис для аудита действий пользователя в ЛК
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.audit.as.as.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * StoreFlUlCreateOrderRequestSpecial
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-19T17:20:45.982+03:00")
public class StoreFlUlCreateOrderRequestSpecial {
  @JsonProperty("oldCustomerId")
  private String oldCustomerId = null;

  @JsonProperty("newCustomerId")
  private String newCustomerId = null;

  @JsonProperty("msisdn")
  private String msisdn = null;

  public StoreFlUlCreateOrderRequestSpecial oldCustomerId(String oldCustomerId) {
    this.oldCustomerId = oldCustomerId;
    return this;
  }

   /**
   * Get oldCustomerId
   * @return oldCustomerId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOldCustomerId() {
    return oldCustomerId;
  }

  public void setOldCustomerId(String oldCustomerId) {
    this.oldCustomerId = oldCustomerId;
  }

  public StoreFlUlCreateOrderRequestSpecial newCustomerId(String newCustomerId) {
    this.newCustomerId = newCustomerId;
    return this;
  }

   /**
   * Get newCustomerId
   * @return newCustomerId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNewCustomerId() {
    return newCustomerId;
  }

  public void setNewCustomerId(String newCustomerId) {
    this.newCustomerId = newCustomerId;
  }

  public StoreFlUlCreateOrderRequestSpecial msisdn(String msisdn) {
    this.msisdn = msisdn;
    return this;
  }

   /**
   * Get msisdn
   * @return msisdn
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMsisdn() {
    return msisdn;
  }

  public void setMsisdn(String msisdn) {
    this.msisdn = msisdn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoreFlUlCreateOrderRequestSpecial storeFlUlCreateOrderRequestSpecial = (StoreFlUlCreateOrderRequestSpecial) o;
    return Objects.equals(this.oldCustomerId, storeFlUlCreateOrderRequestSpecial.oldCustomerId) &&
        Objects.equals(this.newCustomerId, storeFlUlCreateOrderRequestSpecial.newCustomerId) &&
        Objects.equals(this.msisdn, storeFlUlCreateOrderRequestSpecial.msisdn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oldCustomerId, newCustomerId, msisdn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoreFlUlCreateOrderRequestSpecial {\n");

    sb.append("    oldCustomerId: ").append(toIndentedString(oldCustomerId)).append("\n");
    sb.append("    newCustomerId: ").append(toIndentedString(newCustomerId)).append("\n");
    sb.append("    msisdn: ").append(toIndentedString(msisdn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

