/*
 * Audit Service
 * Сервис для аудита действий пользователя в ЛК
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.audit.as.as.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * StoreCallDetalizationRequestSpecial
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-19T17:20:45.982+03:00")
public class StoreCallDetalizationRequestSpecial {
  @JsonProperty("msisdns")
  private List<String> msisdns = new ArrayList<String>();

  public StoreCallDetalizationRequestSpecial msisdns(List<String> msisdns) {
    this.msisdns = msisdns;
    return this;
  }

  public StoreCallDetalizationRequestSpecial addMsisdnsItem(String msisdnsItem) {
    this.msisdns.add(msisdnsItem);
    return this;
  }

   /**
   * Get iccids
   * @return iccids
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getMsisdns() {
    return msisdns;
  }

  public void setMsisdns(List<String> msisdns) {
    this.msisdns = msisdns;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoreCallDetalizationRequestSpecial storeCallDetalizationRequestSpecial = (StoreCallDetalizationRequestSpecial) o;
    return Objects.equals(this.msisdns, storeCallDetalizationRequestSpecial.msisdns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(msisdns);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoreCallDetalizationRequestSpecial {\n");

    sb.append("    msisdns: ").append(toIndentedString(msisdns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

