/*
 * Audit Service
 * Сервис для аудита действий пользователя в ЛК
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.audit.as.as.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * StoreChangeSimRequestSpecial
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-19T17:20:45.982+03:00")
public class StoreChangeSimRequestSpecial {
  @JsonProperty("oldICCID")
  private String oldICCID = null;

  @JsonProperty("newICCID")
  private String newICCID = null;

  public StoreChangeSimRequestSpecial oldICCID(String oldICCID) {
    this.oldICCID = oldICCID;
    return this;
  }

   /**
   * Get oldICCID
   * @return oldICCID
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOldICCID() {
    return oldICCID;
  }

  public void setOldICCID(String oldICCID) {
    this.oldICCID = oldICCID;
  }

  public StoreChangeSimRequestSpecial newICCID(String newICCID) {
    this.newICCID = newICCID;
    return this;
  }

   /**
   * Get newICCID
   * @return newICCID
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNewICCID() {
    return newICCID;
  }

  public void setNewICCID(String newICCID) {
    this.newICCID = newICCID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoreChangeSimRequestSpecial storeChangeSimRequestSpecial = (StoreChangeSimRequestSpecial) o;
    return Objects.equals(this.oldICCID, storeChangeSimRequestSpecial.oldICCID) &&
        Objects.equals(this.newICCID, storeChangeSimRequestSpecial.newICCID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oldICCID, newICCID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoreChangeSimRequestSpecial {\n");

    sb.append("    oldICCID: ").append(toIndentedString(oldICCID)).append("\n");
    sb.append("    newICCID: ").append(toIndentedString(newICCID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

