/*
 * Audit Service
 * Сервис для аудита действий пользователя в ЛК
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.audit.as.as.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * StoreAddProductRequestSpecial
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-19T17:20:45.982+03:00")
public class StoreAddProductRequestSpecial {
  @JsonProperty("iccid")
  private String iccid = null;

  @JsonProperty("offerCode")
  private String offerCode = null;

  @JsonProperty("productId")
  private String productId = null;

  @JsonProperty("option")
  private String option = null;

  public StoreAddProductRequestSpecial iccid(String iccid) {
    this.iccid = iccid;
    return this;
  }

   /**
   * Get iccid
   * @return iccid
  **/
  @ApiModelProperty(required = true, value = "")
  public String getIccid() {
    return iccid;
  }

  public void setIccid(String iccid) {
    this.iccid = iccid;
  }

  public StoreAddProductRequestSpecial offerCode(String offerCode) {
    this.offerCode = offerCode;
    return this;
  }

   /**
   * Get offerCode
   * @return offerCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOfferCode() {
    return offerCode;
  }

  public void setOfferCode(String offerCode) {
    this.offerCode = offerCode;
  }

  public StoreAddProductRequestSpecial productId(String productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Get productId
   * @return productId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getProductId() {
    return productId;
  }

  public void setProductId(String productId) {
    this.productId = productId;
  }

  public StoreAddProductRequestSpecial option(String option) {
    this.option = option;
    return this;
  }

   /**
   * Get option
   * @return option
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOption() {
    return option;
  }

  public void setOption(String option) {
    this.option = option;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoreAddProductRequestSpecial storeAddProductRequestSpecial = (StoreAddProductRequestSpecial) o;
    return Objects.equals(this.iccid, storeAddProductRequestSpecial.iccid) &&
        Objects.equals(this.offerCode, storeAddProductRequestSpecial.offerCode) &&
        Objects.equals(this.productId, storeAddProductRequestSpecial.productId) &&
        Objects.equals(this.option, storeAddProductRequestSpecial.option);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iccid, offerCode, productId, option);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoreAddProductRequestSpecial {\n");

    sb.append("    iccid: ").append(toIndentedString(iccid)).append("\n");
    sb.append("    offerCode: ").append(toIndentedString(offerCode)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    option: ").append(toIndentedString(option)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

