/*
 * Audit Service
 * Сервис для аудита действий пользователя в ЛК
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.audit.as.as.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * StoreResetPasswordRequestSpecial
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-19T17:20:45.982+03:00")
public class StoreResetPasswordRequestSpecial {
  @JsonProperty("wherePasswordSentTo")
  private String wherePasswordSentTo = null;

  public StoreResetPasswordRequestSpecial wherePasswordSentTo(String wherePasswordSentTo) {
    this.wherePasswordSentTo = wherePasswordSentTo;
    return this;
  }

   /**
   * Get wherePasswordSentTo
   * @return wherePasswordSentTo
  **/
  @ApiModelProperty(required = true, value = "")
  public String getWherePasswordSentTo() {
    return wherePasswordSentTo;
  }

  public void setWherePasswordSentTo(String wherePasswordSentTo) {
    this.wherePasswordSentTo = wherePasswordSentTo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoreResetPasswordRequestSpecial storeResetPasswordRequestSpecial = (StoreResetPasswordRequestSpecial) o;
    return Objects.equals(this.wherePasswordSentTo, storeResetPasswordRequestSpecial.wherePasswordSentTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wherePasswordSentTo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoreResetPasswordRequestSpecial {\n");

    sb.append("    wherePasswordSentTo: ").append(toIndentedString(wherePasswordSentTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

