/*
 * Audit Service
 * Сервис для аудита действий пользователя в ЛК
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.audit.as.as.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * StoreAddSimFromBoxRequestSpecial
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-19T17:20:45.982+03:00")
public class StoreAddSimFromBoxRequestSpecial {
  @JsonProperty("mainIccid")
  private String mainIccid = null;

  @JsonProperty("otherIccids")
  private List<String> otherIccids = new ArrayList<String>();

  public StoreAddSimFromBoxRequestSpecial mainIccid(String mainIccid) {
    this.mainIccid = mainIccid;
    return this;
  }

   /**
   * Get mainIccid
   * @return mainIccid
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMainIccid() {
    return mainIccid;
  }

  public void setMainIccid(String mainIccid) {
    this.mainIccid = mainIccid;
  }

  public StoreAddSimFromBoxRequestSpecial otherIccids(List<String> otherIccids) {
    this.otherIccids = otherIccids;
    return this;
  }

  public StoreAddSimFromBoxRequestSpecial addOtherIccidsItem(String otherIccidsItem) {
    this.otherIccids.add(otherIccidsItem);
    return this;
  }

   /**
   * Get otherIccids
   * @return otherIccids
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getOtherIccids() {
    return otherIccids;
  }

  public void setOtherIccids(List<String> otherIccids) {
    this.otherIccids = otherIccids;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoreAddSimFromBoxRequestSpecial storeAddSimFromBoxRequestSpecial = (StoreAddSimFromBoxRequestSpecial) o;
    return Objects.equals(this.mainIccid, storeAddSimFromBoxRequestSpecial.mainIccid) &&
        Objects.equals(this.otherIccids, storeAddSimFromBoxRequestSpecial.otherIccids);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mainIccid, otherIccids);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoreAddSimFromBoxRequestSpecial {\n");

    sb.append("    mainIccid: ").append(toIndentedString(mainIccid)).append("\n");
    sb.append("    otherIccids: ").append(toIndentedString(otherIccids)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

